easy_admin:
    site_name: 'GESTION DES PARAMETRES DU CV'
    design:
        menu: [ 
            { entity: 'Personne', label: 'Gestion des Personnes', icon: 'user'}, 
            { entity: 'Realisation', label: 'Gestion des Realisations', icon: 'tasks'}, 
          ]
    entities:
      Personne:
        class: App\Entity\Personne

      Realisation:
        App\Entity\Realisation
       # List the entity class name you want to manage
       # - App\Entity\Personne
       # - App\Entity\Realisation
       # - App\Entity\User
